name: adguard.txt updater

on:
  push:
    branches: ['main']
    paths: ['debug']

env:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set variables
        run:  |
          echo "DATE=$(date +'%y%m%d%H')" >> $GITHUB_ENV
          echo "DATE2=$(date +'%Y/%m/%d - %H:%S')" >> $GITHUB_ENV
