name: adguard.txt updater

on:
  push:
    branches: ['main']
    paths: ['debug']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: create hosts.tmp
        run:  |
          cp hosts{,.tmp}
          
      - name: add "^" enf of each line
        run:  |
          sed -i s/$/^/ hosts.tmp
          
      - name: replace "127.0.0.1 " with "||"
        run:  |
          sed -i "s/127.0.0.1 /||/" hosts.tmp
      
      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
