name: adguard-hostlistcompiler

on:
  push:
    branches: ['main']
    paths: ['debug']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Run  @adguard/hostlist-compiler
        run:  |
          npm i -g @adguard/hostlist-compiler
          hostlist-compiler -c config.json -o output.txt
          
      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
