name: auto-update-release

on:
  push:
    branches: ['main']
    paths: ['dns']

env:  #ONLY CHANGE THESE 
  ZIP_NAME: "turkish-ad-hosts-magisk-module" #EX: turkish-ad-hosts-magisk-module
  HOSTS_NAME: "Turkish-Ad-Hosts" #EX: Turkish-Ad-Hosts
  MODULE_NAME: "Turkish Ad Hosts" #EX: Turkish Ad Hosts
  MODULE_VER: "1.0.3" #EX: 1.0.0
  AUTHOR: "Ali Beyaz" #EX: Ali Beyaz
  UPDATEJSON_RAW_URL: "https://raw.githubusercontent.com/symbuzzer/Turkish-Ad-Hosts/main/magisk/update.json" #EX: https://raw.githubusercontent.com/symbuzzer/Turkish-Ad-Hosts/main/hosts
  REPO_URL: "https://github.com/symbuzzer/Turkish-Ad-Hosts" #EX: https://github.com/symbuzzer/Turkish-Ad-Hosts
  MODULE_DESC: "Türkiye'de yaygın kullanılan mobil uygulamalardaki (ve muhtemelen WEB sayfalarındaki) izleme (ve beraberinde muhtemelen reklam) ağlarını engellemek için gerekli hosts dosyası"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Set variables
        run:  |
          echo "DATE=$(date +'%y%m%d%H')" >> $GITHUB_ENV
          echo "DATE2=$(date +'%Y/%m/%d - %H:%S')" >> $GITHUB_ENV
          
      - name: Hacking variables ;)
        env:
          DIRTY_PATH: "/releases/download/v"
          DIRTY_SLASH: "/"
          DIRTY_VER: -v
          DIRTY_ZIP: ".zip"
        run:  |
          echo "ZIP_URL=${{env.REPO_URL}}${{env.DIRTY_PATH}}${{env.DATE}}${{Env.DIRTY_SLASH}}${{env.ZIP_NAME}}${{env.DIRTY_VER}}${{env.DATE}}${{env.DIRTY_ZIP}}" >> $GITHUB_ENV
          echo ${{env.ZIP_URL}}
    
      - name: Checkout
        uses: symbuzzer/fork-checkout-repo@main
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Adding prefix to "hosts" file
        run:  |
          echo -e "# Title: Turkish Ad Hosts\n# Author: Ali Beyaz (avalibeyaz.com/github)\n# Author web page: avalibeyaz.com\n# Author e-mail: alipolatbeyaz[@]gmail.com\n# Description: Necessary hosts file to block tracking (and possibly advertising) networks in commonly used mobile applications (and possibly WEB pages) in Turkey\n# Homepage: https://github.com/symbuzzer/Turkish-Ad-Hosts\n# Format: Hosts\n# License: GNU GENERAL PUBLIC LICENSE\n# Version: ${{ env.DATE }}\n# (Version also shows update date as YYMMDDHH)\n# Project start date: 17/11/2022\n# Problematic apps: https://github.com/symbuzzer/Turkish-Ad-Hosts/issues?q=is%3Aissue+is%3Aopen+label%3A%22Problematic+apps+%2F+Sorunlu+uygulamalar%22\n# Wiki: https://github.com/symbuzzer/Turkish-Ad-Hosts/wiki\n# Discussions: https://github.com/symbuzzer/Turkish-Ad-Hosts/discussions\n# Releases: https://github.com/symbuzzer/Turkish-Ad-Hosts/releases\n# Issues: https://github.com/symbuzzer/Turkish-Ad-Hosts/issues\n\n127.0.0.1 localhost\n\n# --- [ START ] --- #" > hosts
          
      - name: Create "hosts" file from "dns" file
        run:  |
          sed -e 's/^/127.0.0.1 /' dns >> hosts
          
      - name: Adding suffix to "hosts" file
        run:  |
          echo -e "# --- [ END ] --- #" >> hosts
          
      - name: Addind version string to "README.md"
        run:  |
          sed -i "3s/.*/# Turkish Ad Hosts - v\$DATE/" README.md
          
      - name: Creating directories
        run:  |
          mkdir -p adguard
          mkdir -p downloads
          mkdir -p magisk
          mkdir -p release
          mkdir -p zip/system/etc
          mkdir -p zip/common
          mkdir -p zip/META-INF/com/google/android          
          
      - name: Downloading "Zackptg5/MMT-Extended" template files from abit modified my own fork
        run:  |
          cd downloads
          wget https://raw.githubusercontent.com/symbuzzer/MMT-Extended-Next/main/uninstall.sh
          wget https://raw.githubusercontent.com/symbuzzer/MMT-Extended-Next/main/customize.sh
          wget https://raw.githubusercontent.com/symbuzzer/MMT-Extended-Next/main/LICENSE
          wget https://raw.githubusercontent.com/symbuzzer/MMT-Extended-Next/main/common/functions.sh
          wget https://raw.githubusercontent.com/symbuzzer/MMT-Extended-Next/main/common/install.sh
          wget https://raw.githubusercontent.com/symbuzzer/MMT-Extended-Next/main/META-INF/com/google/android/update-binary
          wget https://raw.githubusercontent.com/symbuzzer/MMT-Extended-Next/main/META-INF/com/google/android/updater-script

      - name: Downloading "update.json" file
        run:  |
          cd downloads
          wget $UPDATEJSON_RAW_URL
          
      - name: Update "update.json" version
        uses: symbuzzer/fork-action-set-json-field@master
        with:
          file: downloads/update.json
          field: version
          value: v${{ env.DATE }}

      - name: Update "update.json" versionCode
        uses: symbuzzer/fork-action-set-json-field@master
        with:
          file: downloads/update.json
          field: versionCode
          value: ${{ env.DATE }}
          
      - name: Update "update.json" zipUrl
        uses: symbuzzer/fork-action-set-json-field@master
        with:
          file: downloads/update.json
          field: zipUrl
          value: ${{ env.ZIP_URL }}
      
      - name: Create "module.prop" file
        run:  |
          echo "id=$HOSTS_NAME
          name=$MODULE_NAME - v$MODULE_VER
          version=v${{ env.DATE }}
          versionCode=${{ env.DATE }}
          author=$AUTHOR
          description=$MODULE_DESC
          updateJson=$UPDATEJSON_RAW_URL" > module.prop
      
      - name: Copying files to necessary dirs
        run:  |
          sudo cp downloads/update.json magisk/
          sudo cp hosts release/
          sudo cp hosts adguard/
          sudo cp windows/turkish-ad-hosts-windows.bat release/
          sudo cp linux/turkish-ad-hosts-linux.sh release/
          sudo cp hosts zip/system/etc/
          sudo cp magisk/update.json zip/
          sudo mv module.prop zip/
          sudo cp downloads/uninstall.sh zip/
          sudo cp downloads/customize.sh zip/
          sudo cp downloads/LICENSE zip/
          sudo cp downloads/functions.sh zip/common/
          sudo cp downloads/install.sh zip/common/
          sudo cp downloads/update-binary zip/META-INF/com/google/android/
          sudo cp downloads/updater-script zip/META-INF/com/google/android/
          ls -R
                    
      - name: Run @adguard/hostlist-compiler
        run:  |
          cd adguard
          npm i -g @adguard/hostlist-compiler
          hostlist-compiler -c configuration.json -o filter.txt
      
      - name: Copy adguard/filter.txt to releases
        run:  |
          sudo cp adguard/filter.txt release/
          
      - name: Creating module zip
        run:  |
          cd zip
          sudo zip -r -m $ZIP_NAME-v${{ env.DATE }}.zip *
      
      - name: Copy module zip to "release" folder
        run:  |
            sudo cp zip/*.zip release/
          
      - name: Create and upload release asset
        uses: symbuzzer/fork-github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.DATE }}
          name: v${{ env.DATE }}
          body: Hosts file updated to ${{ env.DATE2 }}
          files: release/*
          gzip: false
          draft: false
          prerelease: false
          allow_override: true
          
      - name: Create "version" file
        run:  |
          echo ${{ env.DATE }} > version
          
      - name: Cleanup before commit and push changes to github
        run:  |
          rm -rf zip
          rm -rf downloads
          rm -rf release
          rm -rf adguard/hosts
          ls -R
          
      - name: Commit and push changes
        uses: symbuzzer/fork-push-changes@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
