name: test
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set variables
        run:  |
          echo "DATE=$(date +'%y%m%d%H')" >> $GITHUB_ENV
          echo "MODULENAME=Turkish-Ad-Hosts-Magisk-Module" >> $GITHUB_ENV
          echo $env.MODULENAME
