name: test
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set variables
        env:
          MODULENAME: "Turkish-Ad-Hosts-Magisk-Module"
        run:  |
          echo $MODULENAME
