name: update.json

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
      - name: Set current date as env variable
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Downloading files
        run:  |
          wget https://raw.githubusercontent.com/symbuzzer/Turkish-Ad-Hosts/main/magisk/update.json
          
      - name: Update update.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: update.json
          field: version
          value: v${{ env.DATE }}

      - name: Update update.json versionCode
        uses: jossef/action-set-json-field@v2.1
        with:
          file: update.json
          field: versionCode
          value: ${{ env.DATE }}
      
      - name: Mpve to folder
        run:  |
          mkdir magisk
          sudo mv update.json magisk/
         
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
